all:
  hosts:
    ubuntu2310:
      ansible_host: 192.168.x.x
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    debian12:
      ansible_host: 192.168.x.x
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    centos9s:
      ansible_host: 192.168.x.x
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key