all:
  hosts:
    ubuntu2310:
      ansible_host: 192.168.43.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    debian12:
      ansible_host: 192.168.43.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    centos9s:
      ansible_host: 192.168.43.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key