global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'vms'
    static_configs:
      - targets: ['192.168.43.10:9100', '192.168.43.11:9100', '192.168.43.12:9100']
  - job_name: 'host'
    static_configs:
      - targets: ['192.168.43.189:9100']
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']