---
- name: Install Docker prerequisites
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install Docker
  package:
    name: docker-ce
    state: present
  become: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
  become: yes